<a href="https://colab.research.google.com/github/Yoga1097/MachineLearning/blob/master/Advertising_multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [17]:
dataset = pd.read_csv('Advertising.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  35.7]
 [239.9  41.5

## Splitting the dataset into the Training set and Test set

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [19]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [20]:
y_pred = regressor.predict(x_test)
print(y_pred)

[10.05739563  7.4522807   7.0197076  24.08029725 12.01786259  6.53793858
 12.78286918 15.10974587 10.76974013 16.34357951 22.88297477  9.12924467
 10.46455672 15.48743552 11.58555633 12.17296914 18.76551502 10.78318566
 15.90515992 17.30651279 24.06692057  9.59834224 15.13512211 12.38591525
  5.71360885 15.24749314 12.29402334 20.9421167  13.40991558  9.04348832
 12.89239415 21.40272028 18.13802209 21.17320803  6.56974433  6.14114206
  7.89018394 13.01541434 14.68953791  6.18835143]


In [21]:
print(regressor.intercept_)
print(regressor.coef_)

2.9948930304953336
[ 0.04458402  0.19649703 -0.00278146]


## **Printing the result Vertically in a Column**

In [22]:
print(y_pred.reshape(len(y_pred),1))

[[10.05739563]
 [ 7.4522807 ]
 [ 7.0197076 ]
 [24.08029725]
 [12.01786259]
 [ 6.53793858]
 [12.78286918]
 [15.10974587]
 [10.76974013]
 [16.34357951]
 [22.88297477]
 [ 9.12924467]
 [10.46455672]
 [15.48743552]
 [11.58555633]
 [12.17296914]
 [18.76551502]
 [10.78318566]
 [15.90515992]
 [17.30651279]
 [24.06692057]
 [ 9.59834224]
 [15.13512211]
 [12.38591525]
 [ 5.71360885]
 [15.24749314]
 [12.29402334]
 [20.9421167 ]
 [13.40991558]
 [ 9.04348832]
 [12.89239415]
 [21.40272028]
 [18.13802209]
 [21.17320803]
 [ 6.56974433]
 [ 6.14114206]
 [ 7.89018394]
 [13.01541434]
 [14.68953791]
 [ 6.18835143]]


# **Printing Predicted value VS Test Data**

In [23]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[10.05739563 11.3       ]
 [ 7.4522807   8.4       ]
 [ 7.0197076   8.7       ]
 [24.08029725 25.4       ]
 [12.01786259 11.7       ]
 [ 6.53793858  8.7       ]
 [12.78286918  7.2       ]
 [15.10974587 13.2       ]
 [10.76974013  9.2       ]
 [16.34357951 16.6       ]
 [22.88297477 24.2       ]
 [ 9.12924467 10.6       ]
 [10.46455672 10.5       ]
 [15.48743552 15.6       ]
 [11.58555633 11.8       ]
 [12.17296914 13.2       ]
 [18.76551502 17.4       ]
 [10.78318566  1.6       ]
 [15.90515992 14.7       ]
 [17.30651279 17.        ]
 [24.06692057 26.2       ]
 [ 9.59834224 10.3       ]
 [15.13512211 14.9       ]
 [12.38591525 12.9       ]
 [ 5.71360885  8.1       ]
 [15.24749314 15.2       ]
 [12.29402334 12.6       ]
 [20.9421167  22.6       ]
 [13.40991558 11.6       ]
 [ 9.04348832  8.5       ]
 [12.89239415 12.5       ]
 [21.40272028 23.7       ]
 [18.13802209 16.1       ]
 [21.17320803 21.8       ]
 [ 6.56974433  5.6       ]
 [ 6.14114206  6.7       ]
 [ 7.89018394  9.7       ]
 

## **Making Single Prediction**

In [30]:
print(regressor.intercept_)
print(regressor.coef_)
print(regressor.predict([[1, 78, 100]]))

2.9948930304953336
[ 0.04458402  0.19649703 -0.00278146]
[18.08809932]
