<a href="https://colab.research.google.com/github/Yoga1097/MachineLearning/blob/master/Advertising_multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Advertising.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[  1.  230.1  37.8  69.2]
 [  2.   44.5  39.3  45.1]
 [  3.   17.2  45.9  69.3]
 [  4.  151.5  41.3  58.5]
 [  5.  180.8  10.8  58.4]
 [  6.    8.7  48.9  75. ]
 [  7.   57.5  32.8  23.5]
 [  8.  120.2  19.6  11.6]
 [  9.    8.6   2.1   1. ]
 [ 10.  199.8   2.6  21.2]
 [ 11.   66.1   5.8  24.2]
 [ 12.  214.7  24.    4. ]
 [ 13.   23.8  35.1  65.9]
 [ 14.   97.5   7.6   7.2]
 [ 15.  204.1  32.9  46. ]
 [ 16.  195.4  47.7  52.9]
 [ 17.   67.8  36.6 114. ]
 [ 18.  281.4  39.6  55.8]
 [ 19.   69.2  20.5  18.3]
 [ 20.  147.3  23.9  19.1]
 [ 21.  218.4  27.7  53.4]
 [ 22.  237.4   5.1  23.5]
 [ 23.   13.2  15.9  49.6]
 [ 24.  228.3  16.9  26.2]
 [ 25.   62.3  12.6  18.3]
 [ 26.  262.9   3.5  19.5]
 [ 27.  142.9  29.3  12.6]
 [ 28.  240.1  16.7  22.9]
 [ 29.  248.8  27.1  22.9]
 [ 30.   70.6  16.   40.8]
 [ 31.  292.9  28.3  43.2]
 [ 32.  112.9  17.4  38.6]
 [ 33.   97.2   1.5  30. ]
 [ 34.  265.6  20.    0.3]
 [ 35.   95.7   1.4   7.4]
 [ 36.  290.7   4.1   8.5]
 [ 37.  266.9  43.8   5. ]
 

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [4]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [5]:
y_pred = regressor.predict(x_test)
print(y_pred)

[10.24664397  7.3067958   7.01313011 24.0629912  11.84538583  6.3623126
 12.97367539 15.01392577 10.95137181 16.2302401  22.94764396  9.07892877
 10.29830431 15.372556   11.63358138 12.38729183 18.91996453 10.72601207
 16.03372676 17.36589369 23.85225051  9.51048184 15.25366204 12.2528663
  5.81346738 15.19998588 12.12398331 20.74762723 13.36651757  9.16548788
 13.0430809  21.47977498 18.01828076 21.14170908  6.74096317  5.9527019
  7.82515133 13.21661502 14.72150697  6.18172688]


In [10]:
print(regressor.intercept_)
print(regressor.coef_)

3.2419693672141516
[-0.00222187  0.0445384   0.1962548  -0.00319076]


## **Printing the result Vertically in a Column**

In [6]:
print(y_pred.reshape(len(y_pred),1))

[[10.24664397]
 [ 7.3067958 ]
 [ 7.01313011]
 [24.0629912 ]
 [11.84538583]
 [ 6.3623126 ]
 [12.97367539]
 [15.01392577]
 [10.95137181]
 [16.2302401 ]
 [22.94764396]
 [ 9.07892877]
 [10.29830431]
 [15.372556  ]
 [11.63358138]
 [12.38729183]
 [18.91996453]
 [10.72601207]
 [16.03372676]
 [17.36589369]
 [23.85225051]
 [ 9.51048184]
 [15.25366204]
 [12.2528663 ]
 [ 5.81346738]
 [15.19998588]
 [12.12398331]
 [20.74762723]
 [13.36651757]
 [ 9.16548788]
 [13.0430809 ]
 [21.47977498]
 [18.01828076]
 [21.14170908]
 [ 6.74096317]
 [ 5.9527019 ]
 [ 7.82515133]
 [13.21661502]
 [14.72150697]
 [ 6.18172688]]


# **Printing Predicted value VS Test Data**

In [7]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[10.24664397 11.3       ]
 [ 7.3067958   8.4       ]
 [ 7.01313011  8.7       ]
 [24.0629912  25.4       ]
 [11.84538583 11.7       ]
 [ 6.3623126   8.7       ]
 [12.97367539  7.2       ]
 [15.01392577 13.2       ]
 [10.95137181  9.2       ]
 [16.2302401  16.6       ]
 [22.94764396 24.2       ]
 [ 9.07892877 10.6       ]
 [10.29830431 10.5       ]
 [15.372556   15.6       ]
 [11.63358138 11.8       ]
 [12.38729183 13.2       ]
 [18.91996453 17.4       ]
 [10.72601207  1.6       ]
 [16.03372676 14.7       ]
 [17.36589369 17.        ]
 [23.85225051 26.2       ]
 [ 9.51048184 10.3       ]
 [15.25366204 14.9       ]
 [12.2528663  12.9       ]
 [ 5.81346738  8.1       ]
 [15.19998588 15.2       ]
 [12.12398331 12.6       ]
 [20.74762723 22.6       ]
 [13.36651757 11.6       ]
 [ 9.16548788  8.5       ]
 [13.0430809  12.5       ]
 [21.47977498 23.7       ]
 [18.01828076 16.1       ]
 [21.14170908 21.8       ]
 [ 6.74096317  5.6       ]
 [ 5.9527019   6.7       ]
 [ 7.82515133  9.7       ]
 