<a href="https://colab.research.google.com/github/Yoga1097/MachineLearning/blob/master/Movie_multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_excel('MultipleLinearRegressionMovieData.xls')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

*** No CODEPAGE record, no encoding_override: will use 'ascii'
[[ 85.09999847   8.5          5.0999999 ]
 [106.3000031   12.89999962   5.80000019]
 [ 50.20000076   5.19999981   2.0999999 ]
 [130.6000061   10.69999981   8.39999867]
 [ 54.79999924   3.0999999    2.9000001 ]
 [ 30.29999924   3.5          1.20000005]
 [ 79.40000153   9.19999981   3.70000005]
 [ 91.           9.           7.5999999 ]
 [135.3999939   15.10000038   7.69999981]
 [ 89.30000305  10.19999981   4.5       ]]
[ 4.69999981  8.80000019 15.10000038 12.19999981 10.60000038  3.5
  9.69999981  5.9000001  20.79999924  7.9000001 ]


## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [4]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [5]:
y_pred = regressor.predict(x_test)
print(y_pred)

[ 6.79228712 10.53327692]


## **Printing the result Vertically in a Column**

In [6]:
print(y_pred.reshape(len(y_pred),1))

[[ 6.79228712]
 [10.53327692]]


# **Printing Predicted value with Test Data**

In [10]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 6.79228712 15.10000038]
 [10.53327692 20.79999924]]
